[package]
name = "paperproof_governance_specs"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
paperproof_governance = { local = "../governance" }
Prover = { local = "./vendor/prover", override = true }

[addresses]
specs = "0x0"
