[package]
name = "paperproof_comments"
edition = "2024"
version = "0.0.1"

[dependencies]
paperproof_governance = { local = "../governance" }
pprf = { local = "../../PPRF-token-contracts" }

[addresses]
paperproof_comments = "0x0"
