[package]
name = "paperproof_governance"
edition = "2024"
version = "0.0.1"

[dependencies]
openzeppelin_access = { local = "../../../sui-depends/contracts-sui/contracts/access" }
pprf = { local = "../../../sui-depends/PPRF-token-contracts" }

[addresses]
paperproof_governance = "0x0"
