[package]
name = "paperproof_publishing"
edition = "2024"
version = "0.0.1"

[dependencies]
paperproof_comments = { local = "../comments" }
paperproof_governance = { local = "../governance" }
paperproof_shared_controller = { local = "../shared/controller" }
pprf = { local = "../../PPRF-token-contracts" }

[addresses]
paperproof_publishing = "0x0"
